name: RxSwiftTraining

options:
  deploymentTarget:
    iOS: 14.0
  developmentLanguage: ja

settings:
  base:
    INFOPLIST_FILE: $TARGET_NAME/Info.plist
    MARKETING_VERSION: 1.0.0

packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire
    version: 5.4.1
  MySwiftExtensions:
    url: https://github.com/a-7days-wonder/MySwiftExtensions
    version: 0.0.2
  RxSwift:
    url: https://github.com/ReactiveX/RxSwift
    version: 6.1.0

targets:
  Application:
    type: application
    platform: iOS
    sources: [Application]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shumpei.nagata.RxSwiftTraining
    dependencies:
      - target: Presentation
      - target: Umbrella
    preBuildScripts:
      - script: |
          # NOTE: Apple Silicon Macでのインストール先なので、Intel Macだとダメかも
          if which /opt/homebrew/bin/swiftlint >/dev/null; then
            /opt/homebrew/bin/swiftlint autocorrect --format
            /opt/homebrew/bin/swiftlint
          else
            echo "warning: SwiftLint is not installed. Please install SwiftLint with Homebrew."
          fi
        name: SwiftLint
  DataStore:
    type: library.static # Domainからしか依存されない・Bundleを持たない
    platform: iOS
    sources: [DataStore]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shumpei.nagata.RxSwiftTraining.DataStore
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - package: Alamofire
      - target: Umbrella
  Domain:
    type: library.static # Presentationからしか依存されない・Bundleを持たない
    platform: iOS
    sources: [Domain]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shumpei.nagata.RxSwiftTraining.Domain
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - target: DataStore
      - target: Umbrella
  Presentation:
    type: framework
    platform: iOS
    sources: [Presentation]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shumpei.nagata.RxSwiftTraining.Presentation
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - target: Domain
      - target: Umbrella
  # 複数のStatic Frameworkを一つのDynamic Frameworkにまとめる
  # Reference:
  #   - https://speakerdeck.com/kishikawakatsumi/swiftniokeruinpototorinkufalseshi-zu-miwotan-ru
  #   - https://medium.com/eureka-engineering/create-merged-framework-to-cut-appstartuptime-72ee67b2bbab
  Umbrella: 
    type: framework
    platform: iOS
    sources: [Umbrella]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shumpei.nagata.RxSwiftTraining.Umbrella
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - package: MySwiftExtensions
      - package: RxSwift
      - package: RxSwift
        product: RxCocoa
      - package: RxSwift
        product: RxRelay

schemes:
  RxSwiftTraining-Debug:
    build:
      targets:
        Application: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Debug
    analyze:
      config: Debug
    archive:
      config: Debug
