name: RxSwiftTraining

options:
  deploymentTarget:
    iOS: 14.0
  developmentLanguage: ja

settings:
  base:
    INFOPLIST_FILE: $TARGET_NAME/Info.plist
    MARKETING_VERSION: 1.0.0
    DISABLE_DIAMOND_PROBLEM_DIAGNOSTIC: YES # https://forums.swift.org/t/swift-packages-in-multiple-targets-results-in-this-will-result-in-duplication-of-library-code-errors/34892

packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire
    version: 5.4.1
  MySwiftExtensions:
    url: https://github.com/a-7days-wonder/MySwiftExtensions
    version: 0.0.2
  RxSwift:
    url: https://github.com/ReactiveX/RxSwift
    version: 6.1.0

targets:
  RxSwiftTraining:
    type: application
    platform: iOS
    sources: [RxSwiftTraining]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shumpei.nagata.RxSwiftTraining
    dependencies:
      - target: DataStore
      - target: Domain
      - target: Presentation
    preBuildScripts:
      - script: |
          # NOTE: Apple Silicon Macでのインストール先なので、Intel Macだとダメかも
          if which /opt/homebrew/bin/swiftlint >/dev/null; then
            /opt/homebrew/bin/swiftlint autocorrect --format
            /opt/homebrew/bin/swiftlint
          else
            echo "warning: SwiftLint is not installed. Please install SwiftLint with Homebrew."
          fi
        name: SwiftLint
  DataStore:
    type: framework
    platform: iOS
    sources: [DataStore]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shumpei.nagata.RxSwiftTraining.DataStore
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - package: Alamofire
      - package: RxSwift
        product: RxRelay
      - package: RxSwift
  Domain:
    type: framework
    platform: iOS
    sources: [Domain]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shumpei.nagata.RxSwiftTraining.Domain
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - package: RxSwift
        product: RxRelay
      - package: RxSwift
      - target: DataStore
  Presentation:
    type: framework
    platform: iOS
    sources: [Presentation]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shumpei.nagata.RxSwiftTraining.Presentation
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - package: MySwiftExtensions
      - package: RxSwift
        product: RxCocoa
      - package: RxSwift
        product: RxRelay
      - package: RxSwift
      - target: Domain

schemes:
  RxSwiftTraining-Debug:
    build:
      targets:
        RxSwiftTraining: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Debug
    analyze:
      config: Debug
    archive:
      config: Debug
